#!/usr/bin/env python3
"""Generate TikZ stress lines from support geometry.

The connection schedule below is intentionally explicit: it records which
supports are connected. Endpoint coordinates are derived from named anchors on
the support geometry, so moving a support updates the generated TikZ output.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


OUT_PATH = Path(__file__).with_name("stress-lines.generated.tex")


@dataclass(frozen=True)
class Rect:
    x0: float
    y0: float
    x1: float
    y1: float

    def anchor(self, name: str) -> tuple[float, float]:
        x_mid = (self.x0 + self.x1) / 2
        y_mid = (self.y0 + self.y1) / 2

        anchors = {
            "bottom_left": (self.x0, self.y0),
            "bottom_mid": (x_mid, self.y0),
            "bottom_right": (self.x1, self.y0),
            "right_mid": (self.x1, y_mid),
            "top_right": (self.x1, self.y1),
            "top_mid": (x_mid, self.y1),
            "top_left": (self.x0, self.y1),
            "left_mid": (self.x0, y_mid),
        }
        return anchors[name]


class Wall:
    """Named anchors for the U-shaped wall support."""

    def __init__(self) -> None:
        self.outer_bottom_left = (2.35, 2.20)
        self.outer_bottom_right = (6.20, 2.20)
        self.right_top = (6.20, 4.20)
        self.inner_top_right = (5.83, 4.20)
        self.inner_bottom_right = (5.83, 2.57)
        self.inner_bottom_left = (2.72, 2.57)
        self.inner_top_left = (2.72, 4.20)
        self.left_top = (2.35, 4.20)

    def anchor(self, name: str) -> tuple[float, float]:
        return getattr(self, name)

    def left_edge_at_y(self, y: float) -> tuple[float, float]:
        return (self.outer_bottom_left[0], y)

    def right_edge_at_y(self, y: float) -> tuple[float, float]:
        return (self.outer_bottom_right[0], y)


SUPPORTS = {
    "bottom_left": Rect(0.85, 0.00, 1.25, 0.40),
    "bottom_mid": Rect(5.05, 0.00, 5.45, 0.40),
    "bottom_right": Rect(7.85, 0.00, 8.25, 0.40),
    "left_edge": Rect(0.00, 3.65, 0.40, 4.05),
    "top_edge": Rect(4.10, 4.95, 4.50, 5.35),
    "right_edge": Rect(8.60, 3.35, 9.00, 3.75),
    "center_col": Rect(4.15, 1.05, 4.55, 1.45),
}
WALL = Wall()


def pt(support_name: str, anchor_name: str) -> tuple[float, float]:
    return SUPPORTS[support_name].anchor(anchor_name)


def wall(anchor_name: str) -> tuple[float, float]:
    return WALL.anchor(anchor_name)


def wall_project_left(source: tuple[float, float]) -> tuple[float, float]:
    return WALL.left_edge_at_y(source[1])


def wall_project_right(source: tuple[float, float]) -> tuple[float, float]:
    return WALL.right_edge_at_y(source[1])


def fmt(point: tuple[float, float]) -> str:
    x, y = point
    return f"({x:.2f},{y:.2f})"


def stress_lines() -> list[tuple[tuple[float, float], tuple[float, float]]]:
    left_mid = pt("left_edge", "right_mid")
    right_mid = pt("right_edge", "left_mid")

    return [
        (left_mid, wall_project_left(left_mid)),
        (wall_project_right(right_mid), right_mid),
        (pt("top_edge", "bottom_left"), wall("inner_top_left")),
        (pt("top_edge", "bottom_right"), wall("inner_top_right")),
        (wall("outer_bottom_left"), pt("bottom_left", "top_right")),
        (wall("inner_bottom_left"), pt("center_col", "top_left")),
        (wall("inner_bottom_right"), pt("center_col", "top_right")),
        (wall("outer_bottom_right"), pt("bottom_right", "top_left")),
        (pt("left_edge", "top_right"), wall("left_top")),
        (pt("left_edge", "bottom_right"), wall("outer_bottom_left")),
        (pt("right_edge", "top_left"), wall("right_top")),
        (pt("right_edge", "bottom_left"), wall("outer_bottom_right")),
        (pt("bottom_left", "top_right"), pt("center_col", "bottom_left")),
        (pt("center_col", "bottom_right"), pt("bottom_mid", "top_left")),
        (pt("bottom_mid", "top_right"), pt("bottom_right", "top_left")),
        (pt("center_col", "top_left"), pt("bottom_left", "top_right")),
        (pt("center_col", "top_right"), pt("bottom_right", "top_left")),
    ]


def main() -> None:
    lines = [
        "% Generated by generate_stress_lines.py; do not edit by hand.",
        "\\newcommand{\\drawStressLines}{%",
    ]

    for start, end in stress_lines():
        lines.append(f"\\stressLine{{{fmt(start)}}}{{{fmt(end)}}}")

    lines.append("}")
    OUT_PATH.write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
